[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "python -m spacy download en_core_web_sm"
]

[start]
cmd = "gunicorn app:app --workers=2 --threads=4 --timeout=120 --bind 0.0.0.0:$PORT"
